# Generated by Django 2.1.15 on 2020-01-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingred'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingred',
            new_name='Ingredient',
        ),
    ]
